# Recruiter-facing E2E config:
# Demonstrates the full pipeline inside this repo:
# raw CSV -> LLM sentiment -> factor -> L/S portfolio -> reports

seed: 42

data:
  raw_headlines_csv: "data/sample_headlines.csv"     # small sample so anyone can run
  universe: [AAPL, MSFT, AMZN, GOOGL, META]
  start: "2024-04-01"
  end:   "2024-06-30"
  sentiment_parquet: "data/sentiment_panel.parquet"  # output from the LLM step

llm:
  model_name: "ProsusAI/finbert"   # falls back to SST-2 if not present
  batch_size: 16
  text_column: "headline"
  date_column: "date"
  ticker_column: "ticker"

factor:
  name: "SENT_L1"     # (SENT_SHOCK also supported by the pipeline)
  shock_window: 5

portfolio:
  long_percentile: 0.2
  short_percentile: 0.2
  daily_rebalance: true

reports:
  out_dir: "reports/"
