name: ci

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          pip install ruff black mypy pytest hypothesis coverage[toml] bandit pip-audit

      - name: Run pre-commit (all files)
        run: |
          pre-commit run --all-files

      - name: Run tests
        env:
          # If tests need env vars, set them here or load a test .env
          PYTHONWARNINGS: default
        run: |
          pytest -q --maxfail=1 --disable-warnings

      - name: Security audit (non-blocking initially)
        run: |
          bandit -r . -x tests || true
          pip-audit -s || true
