name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.12"]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev] || pip install -r requirements.txt requirements-dev.txt
          # If you don't have extras/dev, ensure pytest + coverage + pre-commit are installed:
          pip install pytest coverage pytest-cov black ruff mypy pre-commit

      - name: Run tests (coverage enforced by pyproject)
        run: |
          pytest

      - name: Upload coverage artifact (optional)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python-version }}
          path: |
            .coverage
            htmlcov/
          if-no-files-found: ignore

  # Optional: pre-commit on all Python versions? Usually just one.
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: pip
      - name: Install deps
        run: |
          pip install --upgrade pip
          pip install pre-commit
          pre-commit install --install-hooks
      - name: Run pre-commit
        run: pre-commit run --all-files
